### ISSUE TITLE
lineHighlight stands out too much

### ISSUE THREAD

**Issue by notiv-nt** [DankNeon/sublime#2]
It will be better to set color `#4F598742` 

![image](https://user-images.githubusercontent.com/10743009/51441469-152dfc80-1ce3-11e9-8157-6f40f872cf66.png)

### Before:
![image](https://user-images.githubusercontent.com/10743009/51441499-6938e100-1ce3-11e9-92ab-98da518d772d.png)

### After:

![image](https://user-images.githubusercontent.com/10743009/51441481-38f14280-1ce3-11e9-8a8c-f8fecfc0b41b.png)

https://github.com/DankNeon/sublime/blob/362047dbad73dafd77ff3279a617b343698f11c0/Dank_Neon.tmTheme#L24-L25

**Comment by jpetrucciani** [comment]
I agree, this looks better lighter like that. I'll get it updated!

**Comment by jpetrucciani** [comment]
This will be version `0.0.3` available on package control when the package cache updates!
